### ISSUE TITLE
What's the version of OpenFOAM for amgx4foam?

### ISSUE THREAD

**Issue by lj-cug** [maorz1998/amgx4foam#2]
Dear Sir:
    What's the version of OpenFOAM for amgx4foam?
   I want to use this solver.
   Thanks!
Li Jian

**Comment by maorz1998** [comment]
Hi, It supports OpenFoam-V7.

**Comment by lj-cug** [comment]
Have you tested on OpenFOAM-v9?

**Comment by maorz1998** [comment]
Not yet, but I don't expect any issues.

**Comment by lj-cug** [comment]
Thank you buddy!
